export default {
  name: "Liquor Brands",
  cards: [
    { front: "Absolut", back: "Vodka" },
    { front: "Absolut Citron", back: "Vodka" },
    { front: "Angels Envy", back: "Bourbon" },
    { front: "Bacardo/Cruzan 151", back: "Rum" },
    { front: "Bacardi", back: "Rum" },
    { front: "Basil Hayden's", back: "Bourbon" },
    { front: "Beefeaters", back: "Gin" },
    { front: "Belvedere", back: "Vodka" },
    { front: "Blanton's", back: "Bourbon" },
    { front: "Bombay", back: "Gin" },
    { front: "Bombay Sapphire", back: "Gin" },
    { front: "Booker's", back: "Bourbon" },
    { front: "Buffalo Trace", back: "Bourbon" },
    { front: "Bulleit", back: "Bourbon" },
    { front: "Bushmills", back: "Irish Whiskey" },
    { front: "Canadian Club", back: "Canadian Whiskey" },
    { front: "Canadian Mist", back: "Canadian Whiskey" },
    { front: "Captain Morgan", back: "Rum" },
    { front: "Casamigos", back: "Tequila" },
    { front: "Chivas Regal", back: "Scotch Whiskey" },
    { front: "Ciroc", back: "Vodka" },
    { front: "Courvoisier", back: "Cognac" },
    { front: "Crown Royal", back: "Canadian Whiskey" },
    { front: "Cutty Sark", back: "Scotch Whiskey" },
    { front: "Dewar's White Label", back: "Scotch Whiskey" },
    { front: "Don Julio", back: "Tequila" },
    { front: "Dusse", back: "Cognac" },
    { front: "E&J", back: "Brandy" },
    { front: "Finlandia", back: "Vodka" },
    { front: "Gosling's", back: "Rum" },
    { front: "Grey Goose", back: "Vodka" },
    { front: "Glenfidditch", back: "Scotch Whiskey" },
    { front: "Glenlivet", back: "Scotch Whiskey" },
    { front: "Glenmorangie", back: "Scotch Whiskey" },
    { front: "Hennessy", back: "Cognac" },
    { front: "Hendrick's", back: "Gin" },
    { front: "Herradura", back: "Tequila" },
    { front: "Hornito's", back: "Tequila" },
    { front: "J&B", back: "Scotch Whiskey" },
    { front: "Jack Daniels", back: "American Whiskey" },
    { front: "Jameson", back: "Irish Whiskey" },
    { front: "Jim Beam", back: "Bourbon" },
    { front: "Johnnie Walker Red", back: "Scotch Whiskey" },
    { front: "Johnnie Walker Black", back: "Scotch Whiskey" },
    { front: "José Cuervo 1800", back: "Tequila" },
    { front: "José Cuervo Especial Gold", back: "Tequila" },
    { front: "Ketel One", back: "Vodka" },
    { front: "Knob Creek", back: "Bourbon" },
    { front: "Maker's Mark", back: "Bourbon" },
    { front: "Macallan", back: "Scotch Whiskey" },
    { front: "Milagro", back: "Tequila" },
    { front: "Mt. Gay", back: "Rum" },
    { front: "Myers", back: "Rum" },
    { front: "Oban", back: "Scotch Whiskey" },
    { front: "Pappy Van Winkle", back: "Bourbon" },
    { front: "Patron", back: "Tequila" },
    { front: "Plymouth", back: "Gin" },
    { front: "Remy Martin", back: "Cognac" },
    { front: "Sauza", back: "Tequila" },
    { front: "Seagram's 7", back: "American Whiskey" },
    { front: "Seagram's V.O.", back: "Canadian Whiskey" },
    { front: "Skyy", back: "Vodka" },
    { front: "Smirnoff", back: "Vodka" },
    { front: "Southern Comfort", back: "Fruits & Herbs" },
    { front: "Stolichnaya", back: "Vodka" },
    { front: "Svedka", back: "Vodka" },
    { front: "Tanqueray", back: "Gin" },
    { front: "Tito's", back: "Vodka" },
    { front: "Woodford Reserve", back: "Bourbon" },
    { front: "Whistle Pig", back: "Bourbon" },
    { front: "Wild Turkey 101", back: "Bourbon" },
    { front: "Amaretto", back: "Almond" },
    { front: "Aperol", back: "Bitter Orange" },
    { front: "Bailey's Irish Cream", back: "Chocolate & Vanilla" },
    { front: "Benedictine", back: "Sweet Herbs" },
    { front: "Campari", back: "Bitter Orange" },
    { front: "Chambord", back: "Black Raspberry" },
    { front: "Cointreau", back: "Orange" },
    { front: "Creme de Cassis", back: "Black Currant" },
    { front: "Creme de Cacao", back: "Chocolate" },
    { front: "Creme de Menthe", back: "Mint" },
    { front: "Blue Cucaçao", back: "Orange" },
    { front: "Disaronno", back: "Almond" },
    { front: "Drambuie", back: "Honey" },
    { front: "Fireball", back: "Cinnamon" },
    { front: "Frangelico", back: "Hazelnut" },
    { front: "Galliano", back: "Vanilla & Licorice" },
    { front: "Goldschlager", back: "Cinnamon" },
    { front: "Grand Marnier", back: "Burnt Orange" },
    { front: "Hpnotiq", back: "Tropical Fruits" },
    { front: "Jägermeister", back: "Licorice/Herbs" },
    { front: "Kahlua", back: "Coffee" },
    { front: "Malibu", back: "Coconut" },
    { front: "Midori", back: "Honeydew Melon" },
    { front: "Pama", back: "Pomegranate" },
    { front: "Rumple Minze", back: "Mint" },
    { front: "Sambuca", back: "Licorice" },
    { front: "Sloe Gin", back: "Plum" },
    { front: "St. Germain", back: "Elderflower" },
    { front: "Triple Sec", back: "Orange" },
  ],
};
