export default {
  name: "Spanish Words: Animals",
  cards: [
    { front: "fox", back: "el zorro" },
    { front: "mosquito", back: "el mosquito" },
    { front: "dragonfly", back: "la libélula" },
    { front: "wolf", back: "el lobo" },
    { front: "crab", back: "el cangrejo" },
    { front: "horse", back: "el caballo" },
    { front: "squid", back: "el calamar" },
    { front: "bug", back: "el escarabajo" },
    { front: "duck", back: "el pato" },
    { front: "sheep", back: "la oveja" },
    { front: "whale", back: "la ballena" },
    { front: "owl", back: "el búho" },
    { front: "koala", back: "el koala" },
    { front: "polar bear", back: "el oso polar" },
    { front: "shark", back: "el tiburón" },
    { front: "crocodile", back: "el cocodrilo" },
    { front: "raven", back: "el cuervo" },
    { front: "bat", back: "el murciélago" },
    { front: "penguin", back: "el pingüino" },
    { front: "fish (animal)", back: "el pez" },
    { front: "fly", back: "la mosca" },
    { front: "snail", back: "el caracol" },
    { front: "monkey", back: "el mono" },
    { front: "caterpillar", back: "la oruga" },
    { front: "dinosaur", back: "el dinosaurio" },
    { front: "seagull", back: "la gaviota" },
    { front: "dolphin", back: "el delfín" },
    { front: "panda", back: "el panda" },
    { front: "octopus", back: "el pulpo" },
    { front: "cat", back: "el gato" },
    { front: "seal", back: "la foca" },
    { front: "tortoise", back: "la tortuga" },
    { front: "pigeon", back: "la paloma" },
    { front: "cow", back: "la vaca" },
    { front: "hippo", back: "el hipopótamo" },
    { front: "mouse (animal)", back: "el ratón" },
    { front: "chicken (animal)", back: "el pollo" },
    { front: "bear", back: "el oso" },
    { front: "butterfly", back: "la mariposa" },
    { front: "swan", back: "el cisne" },
    { front: "giraffe", back: "la jirafa" },
    { front: "ant", back: "la hormiga" },
    { front: "jellyfish", back: "la medusa" },
    { front: "pig", back: "el cerdo" },
    { front: "frog", back: "la rana" },
    { front: "dog", back: "el perro" },
    { front: "rabbit", back: "el conejo" },
    { front: "sea horse", back: "el caballito de mar" },
    { front: "snake", back: "la serpiente" },
    { front: "kangaroo", back: "el canguro" },
    { front: "spider", back: "la araña" },
    { front: "donkey", back: "el burro" },
    { front: "parrot", back: "el loro" },
    { front: "lion", back: "el león" },
    { front: "elephant", back: "el elefante" },
    { front: "tiger", back: "el tigre" },
    { front: "bee", back: "la abeja" },
  ],
};
