export default {
  name: "Spanish Words: Business",
  cards: [
  { front: "stamp", back: "(el) sello" },
  { front: "signature", back: "(la) firma" },
  { front: "tax", back: "(el) impuesto" },
  { front: "insurance", back: "(el) seguro" },
  { front: "account number", back: "(el) número de cuenta" },
  { front: "salary", back: "(el) salario" },
  { front: "department", back: "(el) departamento" },
  { front: "customer", back: "(el) cliente" },
  { front: "human resources", back: "recursos humanos" },
  { front: "website", back: "(el) sitio web" },
  { front: "accounting", back: "(la) contabilidad" },
  { front: "money", back: "(el) dinero" },
  { front: "letter (post)", back: "(la) carta" },
  { front: "envelope", back: "(el) sobre" },
  { front: "credit card", back: "(la) tarjeta de crédito" },
  { front: "stress", back: "(el) estrés" },
  { front: "url", back: "(la) url" },
  { front: "e-mail address", back: "(la) dirección de correo electrónico" },
  { front: "projector", back: "(el) proyector" },
  { front: "interest", back: "(el) interés" },
  { front: "sales", back: "(las) ventas" },
  { front: "profit", back: "(el) beneficio" },
  { front: "investment", back: "(la) inversión" },
  { front: "office", back: "(la) oficina" },
  { front: "loss", back: "(la) pérdida" },
  { front: "note (information)", back: "(la) nota" },
  { front: "employer", back: "(el) empleador" },
  { front: "loan", back: "(el) préstamo" },
  { front: "staff", back: "(el) personal" },
  { front: "e-mail", back: "(el) correo electrónico" },
  { front: "marketing", back: "(el) marketing" },
  { front: "amount", back: "(la) cantidad" },
  { front: "stock exchange", back: "(la) bolsa" },
  { front: "password", back: "(la) contraseña" },
  { front: "employee", back: "(el) empleado" },
  { front: "IT", back: "(la) informática" },
  { front: "parcel", back: "(el) paquete" },
  { front: "legal department", back: "(el) departamento legal" },
  { front: "business card", back: "(la) tarjeta de negocios" },
  { front: "cash machine", back: "(el) cajero automático" },
  { front: "note (money)", back: "(el) billete" },
  { front: "coin", back: "(la) moneda" },
  { front: "address", back: "(la) dirección" },
  { front: "bank account", back: "(la) cuenta bancaria" },
  { front: "folder (physical)", back: "(la) carpeta" },
  { front: "rubber stamp", back: "(el) sello de goma" },
  { front: "colleague", back: "(el) compañero" },
  { front: "telephone number", back: "(el) número de teléfono" },
  { front: "meeting room", back: "(la) sala de reuniones" },
  { front: "browser", back: "(el) navegador" },
  { front: "presentation", back: "(la) presentación" },
  ],
};
