export default {
  name: "Spanish Words: Devices",
  cards: [
  { front: "hard drive", back: "(el) disco duro" },
  { front: "microwave", back: "(el) microondas" },
  { front: "coffee machine", back: "(la) cafetera" },
  { front: "TV set", back: "(el) televisor" },
  { front: "earphone", back: "(el) auricular" },
  { front: "vacuum cleaner", back: "(la) aspiradora" },
  { front: "radio", back: "(la) radio" },
  { front: "robot", back: "(el) robot" },
  { front: "oven", back: "(el) horno" },
  { front: "fan", back: "(el) ventilador" },
  { front: "laptop", back: "(el) portátil" },
  { front: "air conditioner", back: "(el) aire acondicionado" },
  { front: "keyboard (computer)", back: "(el) teclado" },
  { front: "remote control", back: "(el) control remoto" },
  { front: "hairdryer", back: "(el) secador de pelo" },
  { front: "screen (computer)", back: "(la) pantalla" },
  { front: "scanner", back: "(el) escáner" },
  { front: "fridge", back: "(la) nevera" },
  { front: "kettle", back: "(el) hervidor" },
  { front: "washing machine", back: "(la) lavadora" },
  { front: "loudspeaker", back: "(los) altavoces" },
  { front: "printer", back: "(la) impresora" },
  { front: "cooker", back: "(la) estufa" },
  { front: "USB stick", back: "(la) unidad flash USB" },
  { front: "camera", back: "(la) cámara" },
  { front: "mouse (computer)", back: "(el) ratón" },
  { front: "dishwasher", back: "(el) lavavajillas" },
  { front: "toaster", back: "(la) tostadora" },
  { front: "telephone", back: "(el) teléfono" },
  ],
};
