export default {
  name: "Spanish Words: Food",
  cards: [
  { front: "carrot", back: "(la) zanahoria" },
  { front: "bacon", back: "(el) tocino" },
  { front: "avocado", back: "(el) aguacate" },
  { front: "dessert", back: "(el) postre" },
  { front: "seafood", back: "(los) mariscos" },
  { front: "soup", back: "(la) sopa" },
  { front: "bean", back: "(el) frijol" },
  { front: "salmon", back: "(el) salmón" },
  { front: "soy", back: "(la) soja" },
  { front: "olive", back: "(la) aceituna" },
  { front: "nut", back: "(la) nuez" },
  { front: "garlic", back: "(el) ajo" },
  { front: "beef", back: "(la) carne de res" },
  { front: "flour", back: "(la) harina" },
  { front: "candy", back: "(el) caramelo" },
  { front: "bread", back: "(el) pan" },
  { front: "tuna", back: "(el) atún" },
  { front: "strawberry", back: "(la) fresa" },
  { front: "wine", back: "(el) vino" },
  { front: "ham", back: "(el) jamón" },
  { front: "kiwi", back: "(el) kiwi" },
  { front: "tobacco", back: "(el) tabaco" },
  { front: "chicken (meat)", back: "(el) pollo" },
  { front: "hot dog", back: "(el) perrito caliente" },
  { front: "lettuce", back: "(la) lechuga" },
  { front: "cocktail", back: "(el) cóctel" },
  { front: "oil", back: "(el) aceite" },
  { front: "lemon", back: "(el) limón" },
  { front: "cabbage", back: "(el) repollo" },
  { front: "chips", back: "(las) patatas fritas" },
  { front: "pea", back: "(el) guisante" },
  { front: "pepper (spice)", back: "(la) pimienta" },
  { front: "meat", back: "(la) carne" },
  { front: "wheat", back: "(el) trigo" },
  { front: "cake", back: "(el) pastel" },
  { front: "hazelnut", back: "(la) avellana" },
  { front: "mint", back: "(la) menta" },
  { front: "blueberry", back: "(el) arándano" },
  { front: "popcorn", back: "(las) palomitas de maíz" },
  { front: "egg", back: "(el) huevo" },
  { front: "pudding", back: "(el) pudín" },
  { front: "bamboo (food)", back: "(el) bambú" },
  { front: "leek", back: "(el) puerro" },
  { front: "energy drink", back: "(la) bebida energética" },
  { front: "pepper (vegetable)", back: "(el) pimiento" },
  { front: "cheese", back: "(el) queso" },
  { front: "pineapple", back: "(la) piña" },
  { front: "lemongrass", back: "(la) citronela" },
  { front: "mango", back: "(el) mango" },
  { front: "celery", back: "(el) apio" },
  { front: "sweet potato", back: "(la) batata" },
  { front: "banana", back: "(el) plátano" },
  { front: "turkey", back: "(el) pavo" },
  { front: "peanut", back: "(el) maní" },
  { front: "mustard", back: "(la) mostaza" },
  { front: "salt", back: "(la) sal" },
  { front: "grape", back: "(la) uva" },
  { front: "cauliflower", back: "(la) coliflor" },
  { front: "chili", back: "(el) chile" },
  { front: "orange juice", back: "(el) zumo de naranja" },
  { front: "sandwich", back: "(el) sándwich" },
  { front: "chocolate", back: "(el) chocolate" },
  { front: "apple", back: "(la) manzana" },
  { front: "spaghetti", back: "(los) espagueti" },
  { front: "pumpkin", back: "(la) calabaza" },
  { front: "sausage", back: "(la) salchicha" },
  { front: "grapefruit", back: "(el) pomelo" },
  { front: "mushroom", back: "(la) seta" },
  { front: "cucumber", back: "(el) pepino" },
  { front: "rice", back: "(el) arroz" },
  { front: "whiskey", back: "(el) whisky" },
  { front: "coconut", back: "(el) coco" },
  { front: "date (food)", back: "(el) dátil" },
  { front: "vanilla", back: "(la) vainilla" },
  { front: "onion", back: "(la) cebolla" },
  { front: "menu", back: "(el) menú" },
  { front: "muffin", back: "(el) muffin" },
  { front: "pizza", back: "(la) pizza" },
  { front: "cinnamon", back: "(la) canela" },
  { front: "curry", back: "(el) curry" },
  { front: "aubergine", back: "(la) berenjena" },
  { front: "raspberry", back: "(la) frambuesa" },
  { front: "breakfast", back: "(el) desayuno" },
  { front: "apple juice", back: "(el) zumo de manzana" },
  { front: "butter", back: "(la) mantequilla" },
  { front: "peach", back: "(el) melocotón" },
  { front: "mayonnaise", back: "(la) mayonesa" },
  { front: "bone (food)", back: "(el) hueso" },
  { front: "tofu", back: "(el) tofu" },
  { front: "noodle", back: "(el) fideo" },
  { front: "hot chocolate", back: "(el) chocolate caliente" },
  { front: "burger", back: "(la) hamburguesa" },
  { front: "water", back: "(el) agua" },
  { front: "soy milk", back: "(la) leche de soja" },
  { front: "tea", back: "(el) té" },
  { front: "milk", back: "(la) leche" },
  { front: "water melon", back: "(la) sandía" },
  { front: "salad", back: "(la) ensalada" },
  { front: "potato", back: "(la) patata" },
  { front: "French fries", back: "(las) patatas fritas" },
  { front: "lunch", back: "(el) almuerzo" },
  { front: "tomato sauce", back: "(la) salsa de tomate" },
  { front: "pear", back: "(la) pera" },
  { front: "fig", back: "(el) higo" },
  { front: "corn", back: "(el) maíz" },
  { front: "sugar", back: "(el) azúcar" },
  { front: "lamb", back: "(el) cordero" },
  { front: "dinner", back: "(la) cena" },
  { front: "apricot", back: "(el) albaricoque" },
  { front: "coffee", back: "(el) café" },
  { front: "oat", back: "(la) avena" },
  { front: "chewing gum", back: "(la) goma de mascar" },
  { front: "milkshake", back: "(el) batido" },
  { front: "truffle", back: "(la) trufa" },
  { front: "spinach", back: "(las) espinacas" },
  { front: "yoghurt", back: "(el) yogur" },
  { front: "cookie", back: "(la) galleta" },
  { front: "sushi", back: "(el) sushi" },
  { front: "broccoli", back: "(el) brócoli" },
  { front: "tomato", back: "(el) tomate" },
  { front: "almond", back: "(la) almendra" },
  { front: "ginger", back: "(el) jengibre" },
  { front: "chicken wings", back: "(las) alitas de pollo" },
  { front: "vodka", back: "(el) vodka" },
  { front: "fish (to eat)", back: "(el) pescado" },
  { front: "doughnut", back: "(la) dona" },
  { front: "pork", back: "(el) cerdo" },
  { front: "jam", back: "(la) mermelada" },
  { front: "pancake", back: "(el) panqueque" },
  { front: "rum", back: "(el) ron" },
  { front: "sugar melon", back: "(el) melón dulce" },
  { front: "coke", back: "(la) coca cola" },
  { front: "honey", back: "(la) miel" },
  { front: "cherry", back: "(la) cereza" },
  { front: "vinegar", back: "(el) vinagre" },
  { front: "orange (food)", back: "(la) naranja" },
  { front: "beer", back: "(la) cerveza" },
  { front: "plum", back: "(la) ciruela" },
  { front: "ice cream", back: "(el) helado" },
  ],
};
