export default {
  name: "Spanish Words: Transportation",
  cards: [
  { front: "pedestrian crossing", back: "(el) paso de peatones" },
  { front: "locomotive", back: "(la) locomotora" },
  { front: "motor scooter", back: "(la) moto" },
  { front: "first class", back: "(la) primera clase" },
  { front: "ticket office", back: "(la) taquilla" },
  { front: "airport", back: "(el) aeropuerto" },
  { front: "rear trunk", back: "(el) maletero" },
  { front: "ship", back: "(el) barco" },
  { front: "street light", back: "(la) luz de la calle" },
  { front: "train", back: "(el) tren" },
  { front: "plane", back: "(el) avión" },
  { front: "submarine", back: "(el) submarino" },
  { front: "life jacket", back: "(el) chaleco salvavidas" },
  { front: "traffic jam", back: "(el) atasco" },
  { front: "bus stop", back: "(la) parada de autobús" },
  { front: "helicopter", back: "(el) helicóptero" },
  { front: "construction site", back: "(la) obra" },
  { front: "ferry", back: "(el) transbordador" },
  { front: "tractor", back: "(el) tractor" },
  { front: "petrol station", back: "(la) gasolinera" },
  { front: "bus", back: "(el) autobús" },
  { front: "minibus", back: "(el) microbús" },
  { front: "container", back: "(el) contenedor" },
  { front: "airline", back: "(la) aerolínea" },
  { front: "economy class", back: "(la) clase económica" },
  { front: "tank", back: "(el) tanque" },
  { front: "tyre", back: "(el) neumático" },
  { front: "school bus", back: "(el) autobús escolar" },
  { front: "harbour", back: "(el) puerto" },
  { front: "steering wheel", back: "(el) volante" },
  { front: "container ship", back: "(el) buque portacontenedores" },
  { front: "car", back: "(el) coche" },
  { front: "taxi", back: "(el) taxi" },
  { front: "high-speed train", back: "(el) tren de alta velocidad" },
  { front: "road", back: "(la) carretera" },
  { front: "subway", back: "(el) metro" },
  { front: "lorry", back: "(el) camión" },
  { front: "motorway", back: "(la) autopista" },
  { front: "tram", back: "(el) tranvía" },
  { front: "car park", back: "(el) estacionamiento" },
  { front: "cable car", back: "(el) teleférico" },
  { front: "yacht", back: "(el) yate" },
  { front: "excavator", back: "(la) excavadora" },
  { front: "battery", back: "(la) batería" },
  { front: "trailer", back: "(el) remolque" },
  { front: "traffic light", back: "(el) semáforo" },
  { front: "motor", back: "(el) motor" },
  { front: "seatbelt", back: "(el) cinturón de seguridad" },
  { front: "motorcycle", back: "(la) motocicleta" },
  { front: "lifeboat", back: "(el) bote salvavidas" },
  { front: "cruise ship", back: "(el) crucero" },
  { front: "ticket vending machine", back: "(el) expendedor" },
  { front: "train station", back: "(la) estación de tren" },
  { front: "business class", back: "(la) clase business" },
  { front: "airbag", back: "(el) airbag" },
  { front: "radar", back: "(el) radar" },
  { front: "pavement", back: "(la) acera" },
  { front: "bicycle", back: "(la) bicicleta" },
  ],
};
